/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ServiceType = IDL.Variant({
  'carpetUpholstery' : IDL.Null,
  'other' : IDL.Null,
  'painting' : IDL.Null,
  'deepCleaning' : IDL.Null,
  'pestControl' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'twoBhk' : IDL.Null,
  'villa' : IDL.Null,
  'squareFeet' : IDL.Null,
  'threeBhk' : IDL.Null,
  'oneBhk' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'service' : ServiceType,
  'propertyType' : PropertyType,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'service' : ServiceType,
  'date' : Time,
  'name' : IDL.Text,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ServiceType,
        PropertyType,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addReview' : IDL.Func([IDL.Text, ServiceType, IDL.Nat, IDL.Text], [], []),
  'deleteReview' : IDL.Func([IDL.Text], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getFeaturedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getReviewsByRating' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getReviewsByService' : IDL.Func([ServiceType], [IDL.Vec(Review)], ['query']),
  'getWhatsAppBookingLink' : IDL.Func([ServiceType], [IDL.Text], ['query']),
  'updateReview' : IDL.Func(
      [IDL.Text, IDL.Text, ServiceType, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ServiceType = IDL.Variant({
    'carpetUpholstery' : IDL.Null,
    'other' : IDL.Null,
    'painting' : IDL.Null,
    'deepCleaning' : IDL.Null,
    'pestControl' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'twoBhk' : IDL.Null,
    'villa' : IDL.Null,
    'squareFeet' : IDL.Null,
    'threeBhk' : IDL.Null,
    'oneBhk' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'service' : ServiceType,
    'propertyType' : PropertyType,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'service' : ServiceType,
    'date' : Time,
    'name' : IDL.Text,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ServiceType,
          PropertyType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addReview' : IDL.Func([IDL.Text, ServiceType, IDL.Nat, IDL.Text], [], []),
    'deleteReview' : IDL.Func([IDL.Text], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getFeaturedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getReviewsByRating' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getReviewsByService' : IDL.Func(
        [ServiceType],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getWhatsAppBookingLink' : IDL.Func([ServiceType], [IDL.Text], ['query']),
    'updateReview' : IDL.Func(
        [IDL.Text, IDL.Text, ServiceType, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };