/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'service' : ServiceType,
  'propertyType' : PropertyType,
  'date' : string,
  'name' : string,
  'time' : string,
  'address' : string,
  'notes' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type PropertyType = { 'commercial' : null } |
  { 'twoBhk' : null } |
  { 'villa' : null } |
  { 'squareFeet' : null } |
  { 'threeBhk' : null } |
  { 'oneBhk' : null };
export interface Review {
  'id' : string,
  'service' : ServiceType,
  'date' : Time,
  'name' : string,
  'reviewText' : string,
  'rating' : bigint,
}
export type ServiceType = { 'carpetUpholstery' : null } |
  { 'other' : null } |
  { 'painting' : null } |
  { 'deepCleaning' : null } |
  { 'pestControl' : null };
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBooking' : ActorMethod<
    [string, string, string, ServiceType, PropertyType, string, string, string],
    undefined
  >,
  /**
   * / Add a review to the system.
   */
  'addReview' : ActorMethod<[string, ServiceType, bigint, string], undefined>,
  /**
   * / Delete a review.
   */
  'deleteReview' : ActorMethod<[string], undefined>,
  /**
   * / Get all bookings.
   */
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  /**
   * / Get all reviews.
   */
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  /**
   * / Get featured reviews (up to 5).
   */
  'getFeaturedReviews' : ActorMethod<[], Array<Review>>,
  /**
   * / Get reviews by rating.
   */
  'getReviewsByRating' : ActorMethod<[bigint], Array<Review>>,
  /**
   * / Get approved reviews by service.
   */
  'getReviewsByService' : ActorMethod<[ServiceType], Array<Review>>,
  /**
   * / Get WhatsApp link for booking.
   */
  'getWhatsAppBookingLink' : ActorMethod<[ServiceType], string>,
  /**
   * / Update a review.
   */
  'updateReview' : ActorMethod<
    [string, string, ServiceType, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];