/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'service' : ServiceType,
  'name' : string,
  'email' : string,
  'message' : string,
  'address' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Review {
  'id' : string,
  'service' : ServiceType,
  'date' : Time,
  'name' : string,
  'reviewText' : string,
  'approvalStatus' : boolean,
  'rating' : bigint,
  'photo' : [] | [ExternalBlob],
}
export type ServiceType = { 'carpetUpholstery' : null } |
  { 'commercialCleaning' : null } |
  { 'other' : null } |
  { 'pestControl' : null } |
  { 'residentialDeepCleaning' : null };
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  /**
   * / Add a booking to the system.
   */
  'addBooking' : ActorMethod<
    [string, string, string, ServiceType, string, string],
    undefined
  >,
  /**
   * / Add a review to the system.
   */
  'addReview' : ActorMethod<
    [string, ServiceType, bigint, string, [] | [ExternalBlob]],
    undefined
  >,
  /**
   * / Approve a review for use in system.
   */
  'approveReview' : ActorMethod<[string], undefined>,
  /**
   * / Directly delete a specific review.
   */
  'deleteReview' : ActorMethod<[string], undefined>,
  /**
   * / Query all approved reviews regardless of service.
   */
  'getAllApprovedReviews' : ActorMethod<[], Array<Review>>,
  /**
   * / Expose all bookings in the system.
   */
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getApprovedReviewsByService' : ActorMethod<[ServiceType], Array<Review>>,
  /**
   * / Get a MODIFIED list of up to 5 featured reviews, for use in carousels.
   */
  'getFeaturedReviews' : ActorMethod<[], Array<Review>>,
  /**
   * / Expose all reviews for a specific rating.
   */
  'getReviewsByRating' : ActorMethod<[bigint], Array<Review>>,
  /**
   * / Update a specific review with new information.
   */
  'updateReview' : ActorMethod<
    [string, string, ServiceType, bigint, string, [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];